import asyncio
import math
import time
from dataclasses import dataclass
from typing import List
from collections import deque
from dualmap.entities.request import Request
from dualmap.logger import init_logger
from dualmap.cache_manager.kvcache_store.prefix_kvcache_store import PrefixKvCacheStore
from dualmap.cache_manager.kvcache_store.shared_prefix_kvcache_pool import SharedPrefixKvCachePool

logger = init_logger(__name__)

@dataclass
class Replica:
    def __init__(self, id, tokenizer, args, shared_cache_pool: SharedPrefixKvCachePool = None):
        self.id = id
        self.tokenizer = tokenizer
        self.replica_slo_budget = args.replica_slo_budget
        self.current_budget=args.replica_slo_budget
        self.received_first_req = False
        self.last_prefill_completed_at=-1
        self.last_ttft=0
        self.pending_requests: List[Request] = []
        self.running_requests: List[Request] = []
        self.lock=asyncio.Lock()
        self.enable_shared_kv_pool = getattr(args, "enable_shared_kv_pool", False)
        # In this codebase's shared-memory model, cross-instance reuse is supported
        # whenever shared_kv_pool is enabled.
        self.enable_cross_instance_reuse = getattr(args, "enable_cross_instance_reuse", True)
        self.cache=PrefixKvCacheStore(args)
        self.shared_cache_pool = shared_cache_pool if self.enable_shared_kv_pool else None
        self.block_size=args.block_size
        self.request_timestamps = deque()
        self.window_size = 180  # 180s

    def get_num_cached_tokens(self, prompt_token_ids: List[int]):
        if self.shared_cache_pool is not None:
            cache_view = self.shared_cache_pool.query_prefix(self.id, prompt_token_ids)
            num_cached_blocks = cache_view.total_cached_blocks
        else:
            num_cached_blocks = self.cache.get_num_cached_blocks(prompt_token_ids)
        if num_cached_blocks > 0:
            return num_cached_blocks * self.block_size
        else:
            return -1

    def get_num_recompute_token_ids(self, prompt_token_ids: List[int]):
        # miss tokens: absent from shared pool, must go through prefill/recompute path
        if self.shared_cache_pool is not None:
            cache_view = self.shared_cache_pool.query_prefix(self.id, prompt_token_ids)
            return cache_view.missing_blocks * self.block_size
        num_cached_tokens = self.get_num_cached_tokens(prompt_token_ids)
        if num_cached_tokens > 0 and num_cached_tokens < len(prompt_token_ids):
            return len(prompt_token_ids) - num_cached_tokens
        else:
            return len(prompt_token_ids)

    def get_num_hit_token_ids(self, prompt_token_ids: List[int]):
        return max(0, len(prompt_token_ids) - self.get_num_recompute_token_ids(prompt_token_ids))

    def get_num_local_hit_token_ids(self, prompt_token_ids: List[int]):
        # local reuse tokens: cache blocks already located on this replica
        if self.shared_cache_pool is None:
            return self.get_num_hit_token_ids(prompt_token_ids)
        cache_view = self.shared_cache_pool.query_prefix(self.id, prompt_token_ids)
        return cache_view.local_cached_blocks * self.block_size

    def get_num_remote_hit_token_ids(self, prompt_token_ids: List[int]):
        # cross-instance reuse tokens: blocks generated by other replicas but reusable
        # through the shared pool semantics in this single-process architecture.
        if self.shared_cache_pool is None:
            return 0
        if not self.enable_cross_instance_reuse:
            return 0
        cache_view = self.shared_cache_pool.query_prefix(self.id, prompt_token_ids)
        return cache_view.remote_cached_blocks * self.block_size

    def save_token_ids(self, token_ids: List[int]): 
        if self.shared_cache_pool is not None:
            num_saved_blocks = self.shared_cache_pool.save_decode(self.id, token_ids)
        else:
            num_saved_blocks = self.cache.save(token_ids)
        return num_saved_blocks * self.block_size

    def save_prefill_token_ids(self, request_id, token_ids: List[int]): 
        if self.shared_cache_pool is not None:
            num_saved_blocks = self.shared_cache_pool.save_prefill(self.id, token_ids)
        else:
            num_saved_blocks = self.cache.save_prefill(request_id, token_ids)
        return num_saved_blocks * self.block_size

    async def get_current_budget(self) -> int:
        async with self.lock: 
            return self.current_budget

    def get_num_running_req(self):
        return len(self.running_requests)

    def get_num_running_req_info(self):
        infos = []
        for req in self.running_requests:
            if req is not None:
                infos.append([req._id, len(req._input_ids), req._output_len, round(time.perf_counter()-req._arrived_at,4)])        
        return infos

    def get_running_req_blocks_cnt(self):
        blocks_cnt = 0
        for req in self.running_requests:
            if req is not None:
                blocks_cnt += math.ceil((len(req._input_ids) + req._output_len) / self.block_size)
        return blocks_cnt

    def get_num_pending_req(self):
        return len(self.pending_requests)

    def get_num_pending_req_info(self):
        infos = []
        for req in self.pending_requests:
            if req is not None:
                infos.append([req._id, len(req._input_ids), req._output_len, round(time.perf_counter()-req._arrived_at,4)])        
        return infos

    def get_num_actual_pending_tokens(self):       
        return max(self.replica_slo_budget - self.current_budget, 0)

    def get_num_pending_hit_tokens(self):
        hit_tokens = 0
        for req in self.pending_requests:
            if req is None:
                continue
            req_actual_num_prefill_tokens = getattr(req, "_actual_num_prefill_tokens", 0)
            req_num_prefill_tokens = getattr(req, "_num_prefill_tokens", len(req._input_ids))
            hit_tokens += max(0, req_num_prefill_tokens - req_actual_num_prefill_tokens)
        return hit_tokens

    def get_num_pending_local_hit_tokens(self):
        return sum(max(0, getattr(req, "_local_hit_tokens", 0)) for req in self.pending_requests if req is not None)

    def get_num_pending_remote_hit_tokens(self):
        return sum(max(0, getattr(req, "_remote_hit_tokens", 0)) for req in self.pending_requests if req is not None)

    async def get_load_states(self):
        qps = 0
        async with self.lock:  
            qps = self.get_request_rate()
            if self.last_prefill_completed_at == -1:
                self.last_prefill_completed_at = time.perf_counter()
        return self.current_budget, self.last_prefill_completed_at, self.last_ttft, len(self.pending_requests), qps

    async def complete_request_prefill(self, replica_id, request: Request, ttft: float) -> bool:
        if request is None:
            return False
        # save kv cache into replca's cache
        num_saved_toekens = self.save_prefill_token_ids(request._id, request._input_ids)
        # logger.debug(f"complete_request_prefill:num_saved_toekens={num_saved_toekens}")

        async with self.lock: 
            try:
                self.received_first_req = True
                if request in self.pending_requests:
                    self.current_budget += request._actual_num_prefill_tokens
                    self.pending_requests.remove(request)
                    self.last_prefill_completed_at = time.perf_counter()
                    self.last_ttft = round(ttft,4)
                    logger.debug(f'complete_request_prefill: replica_id=[{replica_id}], request={request._id}, current_budget={request._actual_num_prefill_tokens},'
                                f'last_prefill_completed_at={self.last_prefill_completed_at},last_ttft={self.last_ttft}')

                    # pending_ids = [req._id for req in self.pending_requests]
                    # logger.debug(f"complete_request_prefill - Pending request IDs:replica_id=[{replica_id}], request={request._id},: {pending_ids}")
                    pending_tokens = [req._actual_num_prefill_tokens for req in self.pending_requests]
                    # logger.debug(f"complete_request_prefill - pending_tokens:replica_id=[{self.id}], request={request._id}, num_pending_req={len(pending_tokens)}: {pending_tokens}")
                    logger.debug(f"complete_request_prefill - replica_id=[{self.id}], request={request._id},self.replica_slo_budget-sum_pending_tokens==current_budget:{(self.replica_slo_budget-sum(pending_tokens))==self.current_budget},{self.replica_slo_budget}-{sum(pending_tokens)}=={self.current_budget}")
                    if request not in self.running_requests:
                        self.running_requests.append(request)
                    return True
            except ValueError: 
                return False
            except Exception as e:
                logger.debug(f'complete_request_prefill:Exception: {e}')
        return False

    def complete_request_decode(self, request: Request, output_text: str):
        if request is None:
            return
        if self.shared_cache_pool is not None:
            self.shared_cache_pool.unpin_request(request._id)
        if request in self.running_requests:
            self.running_requests.remove(request)
        output_token_ids = self.tokenizer.encode(output_text)
        token_ids = request._input_ids + output_token_ids
        num_saved_toekens = self.save_token_ids(token_ids)
        logger.debug(f"complete_request_decode:num_saved_toekens={num_saved_toekens}")

    async def add_request(self, request: Request) -> bool:
        if request is None:
            return False
        success = False
        async with self.lock:
            try:
                if request not in self.pending_requests:
                    request._actual_num_prefill_tokens = self.get_num_recompute_token_ids(request._input_ids)
                    request._local_hit_tokens = self.get_num_local_hit_token_ids(request._input_ids)
                    request._remote_hit_tokens = self.get_num_remote_hit_token_ids(request._input_ids)
                    if self.shared_cache_pool is not None:
                        self.shared_cache_pool.pin_request_prefix(
                            request._id,
                            request._input_ids,
                            replica_id=self.id,
                            include_remote=self.enable_cross_instance_reuse,
                        )
                        if self.enable_cross_instance_reuse:
                            request._transferred_kv_tokens = self.shared_cache_pool.ensure_materialized(self.id, request._input_ids) * self.block_size
                        else:
                            request._transferred_kv_tokens = 0
                    self.current_budget -= request._actual_num_prefill_tokens
                    self.pending_requests.append(request)
                    now = time.perf_counter()
                    self.request_timestamps.append(now)
                    self._cleanup_old_requests(now)
                    # pending_ids = [req._id for req in self.pending_requests]
                    # logger.debug(f"add_request - Pending request IDs:replica_id=[{self.id}], request={request._id},{pending_ids}")
                    pending_tokens = [req._actual_num_prefill_tokens for req in self.pending_requests]
                    # logger.debug(f"add_request - pending_tokens:replica_id=[{self.id}], request={request._id}, num_pending_req={len(pending_tokens)}: {pending_tokens}")
                    logger.debug(f"add_request - replica_id=[{self.id}], request={request._id},self.replica_slo_budget-sum_pending_tokens==current_budget:{(self.replica_slo_budget-sum(pending_tokens))==self.current_budget},{self.replica_slo_budget}-{sum(pending_tokens)}=={self.current_budget}")
                    success = True
            except ValueError:
                success = False
            except Exception as e:
                success = False
                logger.debug(f'add_request:Exception: {e}')
        return success

    async def abort_request(self, request: Request) -> bool:
        res = False
        if request is None:
            return False
        async with self.lock:  # 必须加锁保证原子性
            try:
                if request in self.pending_requests:
                    if self.shared_cache_pool is not None:
                        self.shared_cache_pool.unpin_request(request._id)
                    self.current_budget += request._actual_num_prefill_tokens
                    self.pending_requests.remove(request)
                    pending_ids = [req._id for req in self.pending_requests]
                    logger.debug(f"abort_request - Pending request IDs:replica_id=[{self.id}], request={request._id}: {pending_ids}")
                    pending_tokens = [req._actual_num_prefill_tokens for req in self.pending_requests]
                    logger.debug(f"abort_request - pending_tokens:replica_id=[{self.id}], request={request._id}, num_pending_req={len(pending_tokens)}: {pending_tokens}")
                    logger.debug(f"abort_request - replica_id=[{self.id}], request={request._id},self.replica_slo_budget-sum_pending_tokens==current_budget:{(self.replica_slo_budget-sum(pending_tokens))==self.current_budget},{self.replica_slo_budget}-{sum(pending_tokens)}=={self.current_budget}")
                    res = True
                if request in self.running_requests:
                    if self.shared_cache_pool is not None:
                        self.shared_cache_pool.unpin_request(request._id)
                    self.running_requests.remove(request)
                    res = True
            except ValueError:
                return False
            except Exception as e:
                logger.debug(f'abort_request:Exception: {e}')
        return res


    def _cleanup_old_requests(self, current_time: float):
        if not self.request_timestamps or len(self.request_timestamps) == 0:
            return
        cutoff = current_time - self.window_size
        while True:
            try:
                oldest_timestamp = self.request_timestamps[0] if self.request_timestamps and len(self.request_timestamps) else None
                if oldest_timestamp is None or oldest_timestamp >= cutoff:
                    break
                self.request_timestamps.popleft()
            except IndexError:
                break

    def get_request_rate(self) -> float:
        current_time = time.perf_counter()
        if not self.request_timestamps or len(self.request_timestamps) == 0:
            return 0.0
        try:
            oldest_timestamp = self.request_timestamps[0]
        except IndexError:
            return 0.0

        window_duration = min(
            current_time - oldest_timestamp,
            self.window_size
        )
        if window_duration <= 0:
            return 0.0
        return round(len(self.request_timestamps) / window_duration, 4)
